### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by dbaflight** [jhelom/PocketMine-Plugin-LoginAuth#1]
Hello,
I have met this problem while using your plugin:

[Server thread/CRITICAL]: ClassNotFoundException: "Class PDO not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by jhelom** [comment]
Hi

Please install the PDO module.

http://php.net/manual/en/pdo.installation.php
